# Generated by Django 6.0.4 on 2026-05-01 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'ordering': ['-created_at'], 'verbose_name': 'Beneficiary', 'verbose_name_plural': 'Beneficiaries'},
        ),
    ]
