# Generated by Django 5.0.4 on 2026-05-01 08:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DMSConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inactivity_threshold_days', models.PositiveIntegerField(default=90)),
                ('cooling_off_days', models.PositiveIntegerField(default=7)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('WARNING_1', 'Warning 1 (75%)'), ('WARNING_2', 'Warning 2 (90%)'), ('COOLING_OFF', 'Cooling Off'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dms_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DMS Configuration',
                'verbose_name_plural': 'DMS Configurations',
                'db_table': 'dms_config',
            },
        ),
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile'), ('API', 'API')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_hash', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Heartbeat',
                'verbose_name_plural': 'Heartbeats',
                'db_table': 'heartbeats',
                'ordering': ['-timestamp'],
            },
        ),
    ]
