# Generated by Django 5.0.4 on 2026-05-01 10:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('document', 'Document'), ('photo', 'Photo'), ('video', 'Video'), ('voice', 'Voice Note'), ('memory', 'Memory')], max_length=50)),
                ('s3_key', models.CharField(max_length=500)),
                ('encrypted_data_key', models.TextField()),
                ('file_size', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('original_filename', models.CharField(max_length=255)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'uploaded_at'], name='vault_vault_user_id_a860f0_idx')],
            },
        ),
    ]
