# Generated by Django 6.0.4 on 2026-05-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultitem',
            name='item_type',
            field=models.CharField(choices=[('document', 'Document'), ('photo', 'Photo'), ('video', 'Video'), ('voice', 'Voice Note'), ('memory', 'Memory'), ('note', 'Secure Note'), ('message', 'Heir Message')], max_length=50),
        ),
    ]
